project:
  type: website
  output-dir: docs

website:
  title: "Jayden Evans"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - index.qmd
      - about.qmd
      - music.qmd
      - papers.qmd

format:
  html:
    theme: flatly
    mainfont: Merriweather
    css: styles.css
    toc: true
    page-layout: full

editor: visual

