---
title: "Papers"
---

Going into my fourth year at UCSB I have reflected on the papers I have written throughout my time and I want to highlight some of my personal favorites here. They mostly cover sociological, historical, and political topics.

------------------------------------------------------------------------

This paper was for a European History class and covers the history of European Imperialism and some decolonization movements such as the Algerian War.

[Effects of Imperialism](file:///Users/jaydenevans/Downloads/evans_Hist4cPaper.pdf)

For this next paper, I wrote about some African history and how there has been a sort of revisionist history and not only a physical colonization over the people of Africa, but also a colonization of the history.

[Damaging Effects of Colonial Historiography](file:///Users/jaydenevans/Downloads/BL%20ST%2049A%20Research%20Paper.pdf)

Moving into my sociology papers, this one is on Karl Marx's concept of the primitive accumulation of capital covered in volume of his series "Capital".

[Primitive Accumulation](file:///Users/jaydenevans/Downloads/SOC%20185M%20Paper%20(1).pdf)

These next two papers were on films, the first being the film *Hunger* which covers the experiences of IRA prisoners during the hunger strikes amidst the Troubles in Northern Ireland.

[Hunger as an Anti-Carceral Tool](file:///Users/jaydenevans/Downloads/SOC%20146%20Essay.pdf)

This last paper is on the movie *Moonlight* and covers topics of gender, race and class in a character analysis of the protagonist Chiron.

[Gender Under the Moonlight](file:///Users/jaydenevans/Downloads/SOC%20144S%20Paper%20(2).pdf)
